import React, { useContext } from 'react';

import { LanguageContext } from '../../contexts/LanguageContext';

const About = () => {
   const {translations: trans } = useContext(LanguageContext).translations;
   return (
   <>
   <h1>{trans.aboutMe}</h1>
   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi tortor, pulvinar a felis et, finibus cursus mauris. Etiam porttitor diam massa, a dictum nulla posuere nec. Sed non orci eget risus laoreet fermentum. Nulla sodales nisi id sapien ornare, id rhoncus mi ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In in erat quis nisi pulvinar facilisis. Morbi nec justo ante. Praesent rhoncus vulputate eros, quis dictum dui mollis a. Etiam ligula ligula, interdum sed porta ut, sagittis non elit. Integer id tristique nisl, semper pellentesque urna. Pellentesque aliquam urna quis urna rutrum sodales.

   Vestibulum porta, tellus sed mollis pellentesque, est eros pharetra quam, sed ultricies arcu erat vitae felis. Morbi vitae arcu eros. Proin in malesuada enim. Phasellus euismod, est nec cursus rhoncus, ipsum dolor efficitur urna, in egestas ligula quam vulputate tortor. Nunc non libero semper, consequat metus in, tincidunt ante. Aenean iaculis tincidunt purus ut varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis sem ut lectus tincidunt, nec commodo eros tempus. Sed eget varius tortor.
   
   Phasellus interdum cursus ante. Vestibulum ac mollis felis, vel scelerisque nunc. Duis egestas metus nec tellus lobortis, a aliquet nulla scelerisque. Proin accumsan volutpat nisl at posuere. In vitae nibh sed dui auctor mollis. Donec sem sapien, vulputate ut consectetur ut, pellentesque a arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at felis metus. Cras nisl diam, finibus feugiat tellus vel, volutpat dignissim leo. Suspendisse potenti. Vivamus aliquam vulputate dapibus. Aenean nec odio vitae mi placerat lacinia. Sed sit amet nibh tincidunt, tristique ante eget, consequat urna. Praesent ut pharetra eros. Quisque fringilla nec risus quis scelerisque. Duis aliquet justo libero, eget gravida leo vehicula id.
   
   Aliquam odio nisi, ornare eget eros vel, accumsan porta nisl. Sed vel malesuada nunc. Curabitur interdum est et condimentum egestas. Sed id nulla sit amet tellus sagittis porttitor quis eget tellus. Proin quis nisl ac nunc tincidunt aliquam in ut lacus. Sed pretium turpis in mattis lacinia. Pellentesque quis mi vitae neque eleifend viverra. Nam est augue, porttitor nec scelerisque et, cursus vitae odio. Integer mollis est turpis, ut iaculis nulla cursus ut. Nullam vulputate dapibus sapien. In commodo mauris non justo commodo, id vestibulum ante tempus. Praesent fermentum dapibus ligula sit amet rhoncus. Etiam eleifend nisl diam, at tempor augue pretium nec. Etiam iaculis ut velit id accumsan. Maecenas ac odio pellentesque, facilisis enim quis, mattis nisi.
   
   Curabitur sit amet dignissim nisi. Aenean id feugiat ipsum, in elementum dolor. Vivamus eget arcu eget neque vestibulum malesuada. Aenean ullamcorper neque eget consectetur rutrum. Curabitur facilisis iaculis mauris, nec fermentum augue vestibulum ut. Fusce odio nibh, finibus quis ex sed, finibus semper quam. Aenean sodales ipsum non semper sagittis. Nullam vel blandit lorem, vitae gravida ipsum. Aenean volutpat maximus augue non convallis. Pellentesque hendrerit vulputate odio in mollis. Mauris at velit et augue scelerisque egestas
   .</p>
   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi tortor, pulvinar a felis et, finibus cursus mauris. Etiam porttitor diam massa, a dictum nulla posuere nec. Sed non orci eget risus laoreet fermentum. Nulla sodales nisi id sapien ornare, id rhoncus mi ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In in erat quis nisi pulvinar facilisis. Morbi nec justo ante. Praesent rhoncus vulputate eros, quis dictum dui mollis a. Etiam ligula ligula, interdum sed porta ut, sagittis non elit. Integer id tristique nisl, semper pellentesque urna. Pellentesque aliquam urna quis urna rutrum sodales.

   Vestibulum porta, tellus sed mollis pellentesque, est eros pharetra quam, sed ultricies arcu erat vitae felis. Morbi vitae arcu eros. Proin in malesuada enim. Phasellus euismod, est nec cursus rhoncus, ipsum dolor efficitur urna, in egestas ligula quam vulputate tortor. Nunc non libero semper, consequat metus in, tincidunt ante. Aenean iaculis tincidunt purus ut varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis sem ut lectus tincidunt, nec commodo eros tempus. Sed eget varius tortor.

   Phasellus interdum cursus ante. Vestibulum ac mollis felis, vel scelerisque nunc. Duis egestas metus nec tellus lobortis, a aliquet nulla scelerisque. Proin accumsan volutpat nisl at posuere. In vitae nibh sed dui auctor mollis. Donec sem sapien, vulputate ut consectetur ut, pellentesque a arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at felis metus. Cras nisl diam, finibus feugiat tellus vel, volutpat dignissim leo. Suspendisse potenti. Vivamus aliquam vulputate dapibus. Aenean nec odio vitae mi placerat lacinia. Sed sit amet nibh tincidunt, tristique ante eget, consequat urna. Praesent ut pharetra eros. Quisque fringilla nec risus quis scelerisque. Duis aliquet justo libero, eget gravida leo vehicula id.

   Aliquam odio nisi, ornare eget eros vel, accumsan porta nisl. Sed vel malesuada nunc. Curabitur interdum est et condimentum egestas. Sed id nulla sit amet tellus sagittis porttitor quis eget tellus. Proin quis nisl ac nunc tincidunt aliquam in ut lacus. Sed pretium turpis in mattis lacinia. Pellentesque quis mi vitae neque eleifend viverra. Nam est augue, porttitor nec scelerisque et, cursus vitae odio. Integer mollis est turpis, ut iaculis nulla cursus ut. Nullam vulputate dapibus sapien. In commodo mauris non justo commodo, id vestibulum ante tempus. Praesent fermentum dapibus ligula sit amet rhoncus. Etiam eleifend nisl diam, at tempor augue pretium nec. Etiam iaculis ut velit id accumsan. Maecenas ac odio pellentesque, facilisis enim quis, mattis nisi.

   Curabitur sit amet dignissim nisi. Aenean id feugiat ipsum, in elementum dolor. Vivamus eget arcu eget neque vestibulum malesuada. Aenean ullamcorper neque eget consectetur rutrum. Curabitur facilisis iaculis mauris, nec fermentum augue vestibulum ut. Fusce odio nibh, finibus quis ex sed, finibus semper quam. Aenean sodales ipsum non semper sagittis. Nullam vel blandit lorem, vitae gravida ipsum. Aenean volutpat maximus augue non convallis. Pellentesque hendrerit vulputate odio in mollis. Mauris at velit et augue scelerisque egestas
   .</p>

   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi tortor, pulvinar a felis et, finibus cursus mauris. Etiam porttitor diam massa, a dictum nulla posuere nec. Sed non orci eget risus laoreet fermentum. Nulla sodales nisi id sapien ornare, id rhoncus mi ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In in erat quis nisi pulvinar facilisis. Morbi nec justo ante. Praesent rhoncus vulputate eros, quis dictum dui mollis a. Etiam ligula ligula, interdum sed porta ut, sagittis non elit. Integer id tristique nisl, semper pellentesque urna. Pellentesque aliquam urna quis urna rutrum sodales.

   Vestibulum porta, tellus sed mollis pellentesque, est eros pharetra quam, sed ultricies arcu erat vitae felis. Morbi vitae arcu eros. Proin in malesuada enim. Phasellus euismod, est nec cursus rhoncus, ipsum dolor efficitur urna, in egestas ligula quam vulputate tortor. Nunc non libero semper, consequat metus in, tincidunt ante. Aenean iaculis tincidunt purus ut varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis sem ut lectus tincidunt, nec commodo eros tempus. Sed eget varius tortor.

   Phasellus interdum cursus ante. Vestibulum ac mollis felis, vel scelerisque nunc. Duis egestas metus nec tellus lobortis, a aliquet nulla scelerisque. Proin accumsan volutpat nisl at posuere. In vitae nibh sed dui auctor mollis. Donec sem sapien, vulputate ut consectetur ut, pellentesque a arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at felis metus. Cras nisl diam, finibus feugiat tellus vel, volutpat dignissim leo. Suspendisse potenti. Vivamus aliquam vulputate dapibus. Aenean nec odio vitae mi placerat lacinia. Sed sit amet nibh tincidunt, tristique ante eget, consequat urna. Praesent ut pharetra eros. Quisque fringilla nec risus quis scelerisque. Duis aliquet justo libero, eget gravida leo vehicula id.

   Aliquam odio nisi, ornare eget eros vel, accumsan porta nisl. Sed vel malesuada nunc. Curabitur interdum est et condimentum egestas. Sed id nulla sit amet tellus sagittis porttitor quis eget tellus. Proin quis nisl ac nunc tincidunt aliquam in ut lacus. Sed pretium turpis in mattis lacinia. Pellentesque quis mi vitae neque eleifend viverra. Nam est augue, porttitor nec scelerisque et, cursus vitae odio. Integer mollis est turpis, ut iaculis nulla cursus ut. Nullam vulputate dapibus sapien. In commodo mauris non justo commodo, id vestibulum ante tempus. Praesent fermentum dapibus ligula sit amet rhoncus. Etiam eleifend nisl diam, at tempor augue pretium nec. Etiam iaculis ut velit id accumsan. Maecenas ac odio pellentesque, facilisis enim quis, mattis nisi.

   Curabitur sit amet dignissim nisi. Aenean id feugiat ipsum, in elementum dolor. Vivamus eget arcu eget neque vestibulum malesuada. Aenean ullamcorper neque eget consectetur rutrum. Curabitur facilisis iaculis mauris, nec fermentum augue vestibulum ut. Fusce odio nibh, finibus quis ex sed, finibus semper quam. Aenean sodales ipsum non semper sagittis. Nullam vel blandit lorem, vitae gravida ipsum. Aenean volutpat maximus augue non convallis. Pellentesque hendrerit vulputate odio in mollis. Mauris at velit et augue scelerisque egestas
   .</p>
   </>
   );
}

export default About;