export const DO_SOMETHING = 'DO_SOMETHING';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const SET_SERBIAN_LANGUAGE_SAGA = 'SET_SERBIAN_LANGUAGE_SAGA';
export const SET_ENGLISH_LANGUAGE_SAGA = 'SET_ENGLISH_LANGUAGE_SAGA';

export const SET_SERBIAN_LANGUAGE_REDUCER = 'SET_SERBIAN_LANGUAGE_REDUCER';
export const SET_ENGLISH_LANGUAGE_REDUCER = 'SET_ENGLISH_LANGUAGE_REDUCER';